### ISSUE TITLE
Add more fuzzing-like tests

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/smt#31]
e.g. ideally, stuff like https://github.com/lazyledger/smt/issues/25 would be found by this kind of testing

**Comment by tzdybal** [comment]
Always wanted to try [go-fuzz](https://github.com/dvyukov/go-fuzz).

**Comment by odeke-em** [comment]
Thanks for filing this @liamsi! We do have plans to later on add this repository to oss-fuzz.com for continuous fuzzing and also improve fuzz testing in here.

**Comment by liamsi** [comment]
Having this repo on oss-fuzz.com would be even better than what I expected 🚀 it's awesome to your and your team's eyes on this 🙏🏼
