### ISSUE TITLE
Remove or move bench test

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/smt#45]
Does it make sense to make a benchmark test as part of the main test suite? It's not testing any software assurances, and just making running the tests slower.

IMO this should be removed, or moved to a different package.

https://github.com/celestiaorg/smt/pull/42

**Comment by liamsi** [comment]
Tests ran in less than a minute which is still fast enough IMO. But if you want, you can just [skip the test](https://pkg.go.dev/testing#hdr-Skipping). I do think it makes sense to have benchmarks as part of the main test suite.

**Comment by musalbas** [comment]
Right, but shouldn't it at least be in sub-directory/package called bench/ or something? Otherwise it's cluttering the main folder with non-critical code.

**Comment by liamsi** [comment]
Sure, I'd just say benchmarks as long as they do not run annoyingly long, could just stay part of the default test-suite. They are clearly marked as benchmarks via their name so they do not create confusion or anything. 
But yeah, in general, it might to be a good practice to have some more public API test, e.g. by having a dedicated suffix "_test" package. IMO, it's not common to have another special package for tests (which benchmarks are a special case of) unless you are doing integration tests spanning multiple packages. But if you feel really strongly about this, it's up to you.

**Comment by liamsi** [comment]
Also, benchmarks are only:
> executed by the "go test" command when its -bench flag is provided.
https://pkg.go.dev/testing#hdr-Benchmarks
