### ISSUE TITLE
DeleteForRoot is not right

### ISSUE THREAD

**Issue by yydfjt** [celestiaorg/smt#49]
DeleteForRoot is not right, after DeleteForRoot, the value still can be retrieved. In fact, Delete method in MapStore is not called in DeleteForRoot

**Comment by yydfjt** [comment]
The test pass because Delete method in SparseMerkleTree will set defaultValue to root, thus value cannot get from this empty root. This is not correct, root should not set when delete

**Comment by liamsi** [comment]
@yydfjt was this closed because there is no underlying issue?
